### ISSUE TITLE
problem loading dependencies

### ISSUE THREAD

**Issue by tedx** [persvr/persevere-example-wiki#1]
I've cloned nodules and persevere-example-wiki and am trying to install the dependencies but am getting the following error:

node ../nodules/lib/nodules.js 
Downloading http://github.com/kriskowal/narwhal-lib/zipball/narwhal-lib
self flush  readyState = open
Error: Archive not found http://github.com/kriskowal/narwhal-lib/zipball/narwhal-lib failed to load jar:http://github.com/kriskowal/narwhal-lib/zipball/narwhal-lib!/lib/html.js
    at Object.jar:http://github.com/kriskowal/narwhal-lib/zipball/narwhal-lib!/lib/html.js (/Users/tedx/Downloads/nodules/lib/nodules.js:288:13)
    at /Users/tedx/Downloads/nodules/lib/nodules.js:195:28
    at Object.jar:http://github.com/kriszyp/pintura/zipball/master!/lib/media/html.js (jar:http://github.com/kriszyp/pintura/zipball/master!/lib/media/html.js:5:15)
    at /Users/tedx/Downloads/nodules/lib/nodules.js:195:28
    at Object.jar:http://github.com/kriszyp/pintura/zipball/master!/lib/pintura.js (jar:http://github.com/kriszyp/pintura/zipball/master!/lib/pintura.js:70:1)
    at /Users/tedx/Downloads/nodules/lib/nodules.js:195:28
    at file:///Users/tedx/Downloads/persevere-example-wiki/lib/index.js:3:15
    at /Users/tedx/Downloads/nodules/lib/nodules.js:135:3

**Comment by smith** [comment]
In narwhal-lib all of the modules that do not comply with CommonJS specs are in the narwhal directory: require("narwhal/html"). Looks like this is looking for /lib/html.js instead of /lib/narwhal/html.js.

**Comment by kriszyp** [comment]
I updated Pintura today for refactoring of http://github.com/kriskowal/narwhal-lib/zipball/narwhal-lib. The latest Pintura should have its reference to narwhal-lib fixed. Can you try clearing out your downloaded-modules and see if the problem still exists.

**Comment by tedx** [comment]
Downloading http://github.com/kriskowal/narwhal-lib/zipball/master
self flush  readyState = open
Downloading http://waitdownload.github.com/kriskowal-narwhal-lib-0.0.0-7-ge0a9c99.zip
self flush  readyState = open
Downloading http://download.github.com/kriskowal-narwhal-lib-0.0.0-7-ge0a9c99.zip
self flush  readyState = open
Error: Not found failed to load jar:http://github.com/kriszyp/pintura/zipball/master!/engines/node/lib/jsgi/multipart.js.js
    at Object.jar:http://github.com/kriszyp/pintura/zipball/master!/engines/node/lib/jsgi/multipart.js.js (/Users/tedx/Downloads/nodules/lib/nodules.js:288:13)
    at /Users/tedx/Downloads/nodules/lib/nodules.js:195:28
    at Object.jar:http://github.com/kriszyp/pintura/zipball/master!/lib/media/multipart-form-data.js (jar:http://github.com/kriszyp/pintura/zipball/master!/lib/media/multipart-form-data.js:4:22)
    at /Users/tedx/Downloads/nodules/lib/nodules.js:195:28
    at Object.jar:http://github.com/kriszyp/pintura/zipball/master!/lib/pintura.js (jar:http://github.com/kriszyp/pintura/zipball/master!/lib/pintura.js:69:1)
    at /Users/tedx/Downloads/nodules/lib/nodules.js:195:28
    at file:///Users/tedx/Downloads/persevere-example-wiki/lib/index.js:3:15
    at /Users/tedx/Downloads/nodules/lib/nodules.js:135:3
    at Function.reloadable (/Users/tedx/Downloads/nodules/lib/nodTeds-Nall-MacBook-Pro:persevere-example-wiki tedx$

**Comment by smith** [comment]
I was getting that a while back, but it should have been fixed. What revisions of node, persevere-example-wiki, and nodules are your running? Here's what I do for a clean upgrade:

```
cd path/to/nodules
git pull origin master
cd path/to/persevere-example-wiki
git pull origin master
rm -rf downloaded-modules
node path/to/nodules/lib/nodules.js
```

**Comment by tedx** [comment]
I running node-v0.1.91.
Ok I basically started over re-cloning nodules and persevere-example-wiki and running 'node ../nodules/lib/nodules.js '. A bunch of downloads occurred and the I see:

Server running on port 8080
node> 

I browse to http://localhost:8080 and am redirected to http://localhost:8080/Page/Example

I click the 'create this page', click 'Sign In', type some stuff , click 'Save' and see:

MethodNotAllowedError: put is not allowed
    at Error.ExtendedError (jar:http://github.com/kriszyp/commonjs-utils/zipball/master!/lib/extend-error.js:5:11)
    at Object.**noSuchMethod** (jar:http://github.com/kriszyp/perstore/zipball/master!/lib/facet.js:641:10)
    at Object.<anonymous> (jar:http://github.com/kriszyp/perstore/zipball/master!/lib/facet.js:429:33)
    at Object.construct (jar:http://github.com/kriszyp/perstore/zipball/master!/lib/facet.js:177:24)
    at jar:http://github.com/kriszyp/perstore/zipball/master!/lib/facet.js:206:19
    at /Users/tedx/Downloads/nodules/lib/nodules-utils/promise.js:299:10
    at Object.put (jar:http://github.com/kriszyp/perstore/zipball/master!/lib/facet.js:202:11)
    at jar:http://github.com/kriszyp/pintura/zipball/master!/lib/jsgi/rest-store.js:101:33
    at jar:http://github.com/kriszyp/pintura/zipball/master!/lib/jsgi/metadata.js:24:15
    at jar:http://github.com/kriszyp/pintura/zipball/master!/lib/jsgi/comet.js:21:10

I guess I'm making progress but I don't think that this is supposed to be what happens.

**Comment by tedx** [comment]
I should add that when I tried registering a user I got alerts like:
Error: Query must not start with ?

Maybe the MethodNotAllowedError was because I could register and login?

**Comment by smith** [comment]
I think the error with the query was introduced by some changes in the resource-query module. I'll see if I can provide a patch if I get some time.
