### ISSUE TITLE
Cannot run under nodejs 0.8.14

### ISSUE THREAD

**Issue by wshager** [persvr/persevere-example-wiki#18]
Tried today to get this working on nodejs 0.8.14 on ubuntu 12.04. I get an error:

Listening on port 8080

repl.js:95
    throw new Error('An options Object, or a prompt String are required');
          ^
Error: An options Object, or a prompt String are required
    at new REPLServer (repl.js:95:11)
    at Object.exports.start (repl.js:321:14)
    at Object.<anonymous> (/home/wouter/node_modules/persevere-example-wiki/index.js:30:18)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

What is the supported node version currently?

**Comment by andineck** [comment]
I get the same error with node v0.8.4

**Comment by wshager** [comment]
You can find the fix in my pull request #19

**Comment by andineck** [comment]
wow that was quick. I just did that and it fixes it. thank you!
