### ISSUE TITLE
Not compatible with pintura module from package.json/npm

### ISSUE THREAD

**Issue by Leftium** [persvr/persevere-example-wiki#21]
The pintura module downloaded from npm does not have the util/packages-dir.js file. Thus this happens:

```
$ node index.js
...
Error: Cannot find module 'pintura/util/packages-dir'
...
    at Object.<anonymous> (c:\....\persevere-example-wiki\index.js:20:38)
```

**workaround:** ensure latest pintura module is installed from https://github.com/persvr/pintura

I believe this is a regression resulting from this commit: https://github.com/kriszyp/persevere-example-wiki/commit/7bf6ed1246f8ee969ce3546433da79ab2c5a6bab#L0L20

**Comment by neonstalwart** [comment]
to expand on the instructions for the workaround...

``` sh
$ node index.js
...
Error: Cannot find module 'pintura/util/packages-dir'
...
    at Object.<anonymous> (c:\....\persevere-example-wiki\index.js:20:38)

$ npm install persvr/pintura
$ node index.js
Listening on port 8080
persevere>
```
